# Generated by Django 3.1.6 on 2021-02-17 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toDo', '0002_auto_20210217_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(default='uncategorized', on_delete=django.db.models.deletion.PROTECT, to='toDo.category'),
        ),
    ]
