# Generated by Django 3.1.6 on 2021-02-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDo', '0003_auto_20210217_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ManyToManyField(to='toDo.Category'),
        ),
    ]
